routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/exams/forget', 'ExamController@forget');
Route::resource('/exams', 'ExamController');
Route::resource('/questions', 'QuestionController');
Route::get('/exams/{id}/remember', 'ExamController@remember');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{

    public function questions()
    {
      return $this->belongsToMany('App\Question');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function module()
    {
        return $this->belongsTo('App\Module');
    }
}

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{


  public function exams()
  {
      return $this->hasMany('App\Exam');
  }
}

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{

    public function exams()
    {
      return $this->belongsToMany('App\Exam');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function exams()
    {
        return $this->hasMany('App\Exam');
    }
}

app/Http/Controllers/Api/Controller.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Api/ExamController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Exam;

class ExamController extends Controller
{
  public function index()
  {
    return Exam::all();
  }

  public function show($id)
  {


    return Exam::with('module')->find($id);
  }

  public function store(Request $request)
  {
    return Exam::create($request->all());
  }

  public function update(Request $request, $id)
  {
    $Exam = Exam::findOrFail($id);
    $Exam->update($request->all());

    return $Exam;
  }

  public function destroy(Request $request, $id)
  {
    $Exam = Exam::findOrFail($id);
    $Exam->delete();

    return 204;
  }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use App\Exam;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class ExamController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {

    if (Auth::check()) {
      $exams = Exam::with('user', 'module')->paginate(10);

      return view('exam.exams',['exams' => $exams]);
    }

    return view('auth.login');

  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    //
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    //
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Exam  $exam
  * @return \Illuminate\Http\Response
  */
  public function show(Exam $exam)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Exam  $exam
  * @return \Illuminate\Http\Response
  */
  public function edit(Exam $exam)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Exam  $exam
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, Exam $exam)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Exam  $exam
  * @return \Illuminate\Http\Response
  */
  public function destroy(Exam $exam)
  {
    //
  }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $questions = Question::All();

      return view('question.questions',['questions' => $questions]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
    }
}

resources/views/exam/exams.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card card-default">
        <div class="card-header">Dashboard</div>

        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Materia</th>
                <th>Usuario</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($exams as $exam)
              <tr>
                <td>  {{ $exam->title }} </td>
                <td>  {{ $exam->date }} </td>
                <td>  {{ $exam->module->name }} </td>
                <td>  {{ $exam->user->name }} </td>
                <td> <a class="btn btn-primary" {{--href="{{ route('exams.show', $exam->id) }}"--}}> Recordar </a></td>
                <td> <a class="btn btn-danger" {{--href="{{ route('exams.edit', $exam->id) }}"--}}> Borrar </a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
          {{ $exams->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Examen Laravel
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    @auth
                    <ul class="nav navbar-nav">
                        <li><a href="/exams">Exámenes</a></li>
                        <li><a href="/questions">Preguntas</a></li>
                    </ul>
                    @endauth

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/question/questions.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card card-default">
        <div class="card-header">Dashboard</div>

        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Enunciado</th>
                <th>A</th>
                <th>B</th>
                <th>C</th>
                <th>D</th>
                <th>Solucion</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($questions as $question)
              <tr>
                <td>  {{ $question->text }} </td>
                <td @if($question->a === $question->answer) class='bg-success' @endif>  {{ $question->a }} </td>
                <td @if($question->b === $question->answer) class='bg-success' @endif>  {{ $question->b }} </td>
                <td @if($question->c === $question->answer) class='bg-success' @endif>  {{ $question->c }} </td>
                <td @if($question->d === $question->answer) class='bg-success' @endif>  {{ $question->d }} </td>
                <td>  {{ $question->answer }} </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection